### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Aspire1Inspire2** [TiagoSantos81/libregrammar#1]
Hi @TiagoSantos81, this looks very promising.
Is there any docker image available to let user try out your repo?

**Comment by TiagoSantos81** [comment]
Hi @Aspire1Inspire2 ,

At the moment the project is "frozen". No time to deal with it, but if you make a docker image with verified integrity, I will be happy to link to it in the README.

**Comment by py-crash** [comment]
I wrote a Docker file. I'm not providing an image, but it can be built if someone wants to use it: https://github.com/py-crash/docker-libregrammar

**Comment by Aspire1Inspire2** [comment]
> I wrote a Docker file. I'm not providing an image, but it can be built if someone wants to use it: https://github.com/py-crash/docker-libregrammar

Thank you for your work, both @TiagoSantos81 and @py-crash. I'll try out the docker build and let you know about it.

**Comment by TiagoSantos81** [comment]
@py-crash Thank you! I will link to it on the main page.

**Comment by Aspire1Inspire2** [comment]
Hi, I can confirm that the docker image built works correctly with my chrome LanguageTool extension. I use Apache reverse proxy + Docker. Thanks for the awesome work!

**Comment by Aspire1Inspire2** [comment]
I will close this ticket since the Docker image already works as it is supposed to be.
