### ISSUE TITLE
Can you recommend a new fork?

### ISSUE THREAD

**Issue by phirestalker** [TiagoSantos81/libregrammar#8]
Since this project is abandoned, can you recommend a fork that aims to contain premium features that have been deliberately kept out of the open-source code as your fork does?

**Comment by TiagoSantos81** [comment]
As far as I know, nothing similar is around. Note that LibreGrammar is more than just reactivating rules. It has its own new code and rules. I have not followed LanguageTool development, but the main Languages that concern me the most -- Portuguese and English -- do not have much room for improvement anyway, so LibreGrammar version 5.1 should be adequate. If not, please tell me which feature/rules you are missing.

**Comment by phirestalker** [comment]
I just assumed because they are on version 5.8 (I think) that there were more grammar checks. I am not sure how to check or compare. I saw something about Wikipedia rule gathering, is that something that can glean rules from Wikipedia and can be updated by running some script?
I had originally used Grammarly for my first two years of college, so I went looking for an alternative. I found Languagetool which claimed to be open-source, but they keep stuff for their paid version. I am not even sure if their paid version is on par with Grammarly.
To their and your credit, LibreGrammar seems to have caught everything necessary for my coursework, as I have not been marked for grammar. I guess the main thing that concerned me was it marking things that were not wrong. It marks the word page even though I have it on American English.
Anyway, thanks for the reply.

**Comment by TiagoSantos81** [comment]
>  LibreGrammar seems to have caught everything necessary for my coursework, as I have not been marked for grammar

That is the point;)

**Comment by phirestalker** [comment]
I just thought about how grammar rules change over time. I remember seeing something in the code about Wikipedia scanning. Is there some script I can run to update the grammar rules that does not require recompiling or editing the code? If so, can you point me to the instructions?

**Comment by TiagoSantos81** [comment]
Check this project [https://github.com/cdbeland/moss](https://github.com/cdbeland/moss)
Most scripts do what you want on wikipedia. 
If you want to pass them to LibreGrammar, add to replace.txt on each language module pairs like in
[https://github.com/TiagoSantos81/libregrammar/blob/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wikipedia.txt](https://github.com/TiagoSantos81/libregrammar/blob/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wikipedia.txt)

For example:
wrong=right

You can use simple regular expressions on a text editor for that effect.
For example, go to:
[https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/Grammar_and_miscellaneous](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/Grammar_and_miscellaneous)
and replace the list you find there by copying the list to Notepad++.
Then replace
`^ {4}(.+?)\s*\((.+?)[\),].*?\r\n`
by
`\1=\2\r\n`

**Comment by TomLucidor** [comment]
@TiagoSantos81 could you asee i this is a good alt? They might replace LanguageTool as the next FOSS Grammar checker https://github.com/Automattic/harper

**Comment by TiagoSantos81** [comment]
Hi @TomLucidor! 

Apologies for the delay. I am not familiar with forks, as `libregrammar` has served me right in the last few year as a local server, and I have not felt the need to improve it further.
I am not familiar with Harper, but it seems far more limited in scope. If I am not missing something, it only  covers English and it has much less rules than existing alternatives. In my mind, despite the performance gains, even though I do not endorse LanguageTool, going even from it to Harper would be step back in terms of function.
